# golangci-lint configuration for worktree-container
# Documentation: https://golangci-lint.run/usage/configuration/
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Reports suspicious constructs
    - staticcheck    # Advanced static analysis
    - unused         # Find unused code
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments
    - typecheck      # Type checking
    - gocritic       # Opinionated code reviewer
    - gofmt          # Check formatting
    - misspell       # Find misspelled words in comments
    - exportloopref  # Detect loop variable capture in closures

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment  # Not useful for this project

  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - ifElseChain     # Allow if-else chains for readability
      - hugeParam       # Allow large params in some cases

  errcheck:
    check-type-assertions: true
    check-blank: false

issues:
  exclude-rules:
    # Allow unused params in test files (common in table-driven tests).
    - path: _test\.go
      linters:
        - unused
        - gocritic

    # Allow dot imports in test files for testify.
    - path: _test\.go
      text: "dot-imports"

  max-issues-per-linter: 50
  max-same-issues: 10
