# golangci-lint configuration for worktree-container
# Documentation: https://golangci-lint.run/docs/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Reports suspicious constructs
    - staticcheck    # Advanced static analysis
    - unused         # Find unused code
    - ineffassign    # Detect ineffectual assignments
    - gocritic       # Opinionated code reviewer
    - misspell       # Find misspelled words in comments
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment  # Not useful for this project
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - ifElseChain     # Allow if-else chains for readability
    errcheck:
      check-type-assertions: true
      check-blank: false
  exclusions:
    rules:
      # Allow unused params in test files (common in table-driven tests).
      - path: _test\.go
        linters:
          - unused
          - gocritic
      # Allow dot imports in test files for testify.
      - path: _test\.go
        text: "dot-imports"

formatters:
  enable:
    - gofmt          # Check formatting
