# GoReleaser configuration for worktree-container
# Documentation: https://goreleaser.com
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: worktree-container
    main: ./cmd/worktree-container
    binary: worktree-container
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - repository:
      owner: shinji-kodama
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/shinji-kodama/worktree-container"
    description: "Git worktree-aware Dev Container environment manager"
    license: "MIT"
    install: |
      bin.install "worktree-container"
    test: |
      system "#{bin}/worktree-container", "--version"
